# Generated by Django 5.2.11 on 2026-02-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_alter_camera_stream_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_logout', models.BooleanField(default=True)),
                ('session_timeout', models.IntegerField(default=30)),
                ('password_min_length', models.IntegerField(default=8)),
            ],
            options={
                'verbose_name': 'System Settings',
            },
        ),
    ]
