# Generated by Django 5.2.11 on 2026-02-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='confidence_threshold',
            field=models.FloatField(default=0.6),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='data_retention_days',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='send_cooldown_seconds',
            field=models.IntegerField(default=3.0),
        ),
    ]
