# Generated by Django 5.2.11 on 2026-02-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_systemsettings_confidence_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ocr_confidence',
            field=models.FloatField(default=0.5),
        ),
    ]
