# Generated by Django 5.2.11 on 2026-03-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_systemsettings_ocr_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='conf_helmet',
            field=models.FloatField(default=0.6),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='conf_no_helmet',
            field=models.FloatField(default=0.55),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='conf_nutshell',
            field=models.FloatField(default=0.65),
        ),
    ]
