# Generated by Django 5.2.11 on 2026-03-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_systemsettings_conf_helmet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='conf_license_plate',
            field=models.FloatField(default=0.6),
        ),
    ]
