# Generated by Django 5.2.11 on 2026-04-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0008_remove_session_timeout_auto_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='database_backup_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='database_backup_frequency_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='database_backup_retention_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_on_camera_offline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_on_new_detection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_on_operator_activity',
            field=models.BooleanField(default=True),
        ),
    ]
