# Generated by Django 4.2.8 on 2026-06-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0011_repair_camera_lens_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='rtsp_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
