# Generated by Django 4.2.8 on 2026-07-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0012_camera_rtsp_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='send_cooldown_seconds',
            field=models.FloatField(default=3.0),
        ),
    ]
