# Generated by Django 5.2.11 on 2026-04-09 06:03

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_adminnotification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_preferences',
            field=models.JSONField(blank=True, default=users.models.get_default_display_preferences),
        ),
    ]
