# Generated by Django 4.2.8 on 2026-07-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_display_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_detection', 'New Detection'), ('violation_action', 'Violation Action'), ('evidence_view', 'Evidence View'), ('plate_search', 'Plate Search'), ('report_export', 'Report Export'), ('settings_changed', 'Settings Changed')], default='violation_action', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'TMC Administrator'), ('tmc_operator', 'TMC Operator')], default='tmc_operator', max_length=20),
        ),
    ]
