# Generated by Django 4.2.8 on 2026-07-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_adminnotification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('admin_update', 'Admin Update'), ('new_detection', 'New Detection'), ('system_alert', 'System Alert'), ('settings_changed', 'Settings Changed')], default='admin_update', max_length=50),
        ),
    ]
