# Generated by Django 4.2.8 on 2026-09-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usernotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_detection', 'New Detection'), ('violation_action', 'Violation Action'), ('evidence_view', 'Evidence View'), ('plate_search', 'Plate Search'), ('report_export', 'Report Export'), ('settings_changed', 'Settings Changed'), ('user_login', 'User Login')], default='violation_action', max_length=50),
        ),
    ]
