# Generated by Django 4.2.8 on 2026-09-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_adminnotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_detection', 'New Detection'), ('violation_action', 'Violation Action'), ('evidence_view', 'Evidence View'), ('plate_search', 'Plate Search'), ('report_export', 'Report Export'), ('settings_changed', 'Settings Changed'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('violation_deleted', 'Violation Deleted'), ('evidence_download', 'Evidence Download'), ('user_account_created', 'User Account Created'), ('user_approved', 'User Approved'), ('user_rejected', 'User Rejected'), ('user_deleted', 'User Deleted'), ('user_permissions_changed', 'User Permissions Changed'), ('camera_created', 'Camera Created'), ('camera_updated', 'Camera Updated'), ('camera_deleted', 'Camera Deleted')], default='violation_action', max_length=50),
        ),
    ]
