# Generated by Django 6.0.2 on 2026-02-04 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField()),
                ('detection_status', models.CharField(choices=[('compliant', 'Compliant'), ('violation', 'Violation')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('classification', models.CharField(choices=[('no_helmet', 'No Helmet'), ('nutshell', 'Nutshell Helmet'), ('half_face_helmet', 'Half Face Helmet'), ('full_face_helmet', 'Full Face Helmet')], max_length=50)),
                ('plate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('evidence_image', models.ImageField(blank=True, upload_to='violations/%Y/%m/%d/')),
                ('bounding_box', models.JSONField(blank=True, null=True)),
                ('detected_objects', models.JSONField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='cameras.camera')),
            ],
            options={
                'db_table': 'violations',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['-detected_at'], name='violations_detecte_668639_idx'), models.Index(fields=['detection_status'], name='violations_detecti_784922_idx'), models.Index(fields=['camera'], name='violations_camera__dcd7bf_idx')],
            },
        ),
    ]
