# Generated by Codex on 2026-03-20

from django.db import migrations, models


def migrate_classification_values(apps, schema_editor):
    Violation = apps.get_model("violations", "Violation")

    Violation.objects.filter(classification="half_face_helmet").update(classification="helmet")
    Violation.objects.filter(classification="full_face_helmet").update(classification="helmet")
    Violation.objects.filter(classification="hat").update(classification="no_helmet")

class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0003_violation_reviewed_at_violation_reviewed_by"),
    ]

    operations = [
        migrations.RunPython(
            migrate_classification_values,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="violation",
            name="classification",
            field=models.CharField(
                choices=[
                    ("no_helmet", "No Helmet"),
                    ("helmet", "Helmet"),
                    ("nutshell", "Nutshell"),
                    ("license_plate", "License Plate"),
                ],
                max_length=50,
            ),
        ),
    ]
