# Generated by Django 4.2.8 on 2026-08-17 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('violations', '0005_violation_plate_crop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='plate_corrected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='violation',
            name='plate_corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plate_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='violation',
            name='plate_number_corrected',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
